CREATE TABLE `mdl_tool_brickfield_areas` (
  `id` bigint(10) NOT NULL AUTO_INCREMENT,
  `type` tinyint(2) NOT NULL DEFAULT 0,
  `contextid` bigint(10) DEFAULT NULL,
  `component` varchar(100) DEFAULT NULL,
  `tablename` varchar(40) DEFAULT NULL,
  `fieldorarea` varchar(50) DEFAULT NULL,
  `itemid` bigint(10) DEFAULT NULL,
  `filename` varchar(1333) DEFAULT NULL,
  `reftable` varchar(40) DEFAULT NULL,
  `refid` bigint(10) DEFAULT NULL,
  `cmid` bigint(10) DEFAULT NULL,
  `courseid` bigint(10) DEFAULT NULL,
  `categoryid` bigint(10) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `mdl_toolbricarea_coucmi_ix` (`courseid`,`cmid`),
  KEY `mdl_toolbricarea_typtabitef_ix` (`type`,`tablename`,`itemid`,`fieldorarea`),
  KEY `mdl_toolbricarea_typconcomf_ix` (`type`,`contextid`,`component`,`fieldorarea`,`itemid`),
  KEY `mdl_toolbricarea_refreftyp_ix` (`reftable`,`refid`,`type`),
  KEY `mdl_toolbricarea_cou_ix` (`courseid`),
  KEY `mdl_toolbricarea_cmi_ix` (`cmid`),
  KEY `mdl_toolbricarea_cat_ix` (`categoryid`),
  KEY `mdl_toolbricarea_con_ix` (`contextid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=COMPRESSED COMMENT='Areas that have been checked for accessibility problems'