CREATE TABLE `mdl_tool_brickfield_summary` (
  `id` bigint(10) NOT NULL AUTO_INCREMENT,
  `courseid` bigint(10) NOT NULL,
  `status` tinyint(1) DEFAULT NULL,
  `activities` bigint(10) DEFAULT NULL,
  `activitiespassed` bigint(10) DEFAULT NULL,
  `activitiesfailed` bigint(10) DEFAULT NULL,
  `errorschecktype1` bigint(10) DEFAULT NULL,
  `errorschecktype2` bigint(10) DEFAULT NULL,
  `errorschecktype3` bigint(10) DEFAULT NULL,
  `errorschecktype4` bigint(10) DEFAULT NULL,
  `errorschecktype5` bigint(10) DEFAULT NULL,
  `errorschecktype6` bigint(10) DEFAULT NULL,
  `errorschecktype7` bigint(10) DEFAULT NULL,
  `failedchecktype1` bigint(10) DEFAULT NULL,
  `failedchecktype2` bigint(10) DEFAULT NULL,
  `failedchecktype3` bigint(10) DEFAULT NULL,
  `failedchecktype4` bigint(10) DEFAULT NULL,
  `failedchecktype5` bigint(10) DEFAULT NULL,
  `failedchecktype6` bigint(10) DEFAULT NULL,
  `failedchecktype7` bigint(10) DEFAULT NULL,
  `percentchecktype1` bigint(10) DEFAULT NULL,
  `percentchecktype2` bigint(10) DEFAULT NULL,
  `percentchecktype3` bigint(10) DEFAULT NULL,
  `percentchecktype4` bigint(10) DEFAULT NULL,
  `percentchecktype5` bigint(10) DEFAULT NULL,
  `percentchecktype6` bigint(10) DEFAULT NULL,
  `percentchecktype7` bigint(10) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `mdl_toolbricsumm_sta_ix` (`status`),
  KEY `mdl_toolbricsumm_cou_ix` (`courseid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=COMPRESSED COMMENT='Contains accessibility check results summary information.'