CREATE TABLE `mdl_reportbuilder_schedule` (
  `id` bigint(10) NOT NULL AUTO_INCREMENT,
  `reportid` bigint(10) NOT NULL DEFAULT 0,
  `name` varchar(255) NOT NULL DEFAULT '',
  `enabled` tinyint(1) NOT NULL DEFAULT 1,
  `audiences` longtext NOT NULL,
  `format` varchar(255) NOT NULL DEFAULT '',
  `subject` varchar(255) NOT NULL DEFAULT '',
  `message` longtext NOT NULL,
  `messageformat` bigint(10) NOT NULL,
  `userviewas` bigint(10) NOT NULL DEFAULT 0,
  `timescheduled` bigint(10) NOT NULL DEFAULT 0,
  `recurrence` bigint(10) NOT NULL DEFAULT 0,
  `reportempty` bigint(10) NOT NULL DEFAULT 0,
  `timelastsent` bigint(10) NOT NULL DEFAULT 0,
  `timenextsend` bigint(10) NOT NULL DEFAULT 0,
  `usercreated` bigint(10) NOT NULL DEFAULT 0,
  `usermodified` bigint(10) NOT NULL DEFAULT 0,
  `timecreated` bigint(10) NOT NULL DEFAULT 0,
  `timemodified` bigint(10) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `mdl_reposche_rep_ix` (`reportid`),
  KEY `mdl_reposche_use_ix` (`userviewas`),
  KEY `mdl_reposche_use2_ix` (`usercreated`),
  KEY `mdl_reposche_use3_ix` (`usermodified`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=COMPRESSED COMMENT='Table to represent a report schedule'