CREATE TABLE `mdl_h5p_libraries` (
  `id` bigint(10) NOT NULL AUTO_INCREMENT,
  `machinename` varchar(255) NOT NULL DEFAULT '',
  `title` varchar(255) NOT NULL DEFAULT '',
  `majorversion` smallint(4) NOT NULL,
  `minorversion` smallint(4) NOT NULL,
  `patchversion` smallint(4) NOT NULL,
  `runnable` tinyint(1) NOT NULL,
  `fullscreen` tinyint(1) NOT NULL DEFAULT 0,
  `embedtypes` varchar(255) NOT NULL DEFAULT '',
  `preloadedjs` longtext DEFAULT NULL,
  `preloadedcss` longtext DEFAULT NULL,
  `droplibrarycss` longtext DEFAULT NULL,
  `semantics` longtext DEFAULT NULL,
  `addto` longtext DEFAULT NULL,
  `coremajor` smallint(4) DEFAULT NULL,
  `coreminor` smallint(4) DEFAULT NULL,
  `metadatasettings` longtext DEFAULT NULL,
  `tutorial` longtext DEFAULT NULL,
  `example` longtext DEFAULT NULL,
  `enabled` tinyint(1) DEFAULT 1,
  PRIMARY KEY (`id`),
  KEY `mdl_h5plibr_macmajminpatrun_ix` (`machinename`,`majorversion`,`minorversion`,`patchversion`,`runnable`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=COMPRESSED COMMENT='Stores information about libraries used by H5P content.'