CREATE TABLE `mdl_lesson` (
  `id` bigint(10) NOT NULL AUTO_INCREMENT,
  `course` bigint(10) NOT NULL DEFAULT 0,
  `name` varchar(255) NOT NULL DEFAULT '',
  `intro` longtext DEFAULT NULL,
  `introformat` smallint(4) NOT NULL DEFAULT 0,
  `practice` smallint(3) NOT NULL DEFAULT 0,
  `modattempts` smallint(3) NOT NULL DEFAULT 0,
  `usepassword` smallint(3) NOT NULL DEFAULT 0,
  `password` varchar(32) NOT NULL DEFAULT '',
  `dependency` bigint(10) NOT NULL DEFAULT 0,
  `conditions` longtext NOT NULL,
  `grade` bigint(10) NOT NULL DEFAULT 0,
  `custom` smallint(3) NOT NULL DEFAULT 0,
  `ongoing` smallint(3) NOT NULL DEFAULT 0,
  `usemaxgrade` smallint(3) NOT NULL DEFAULT 0,
  `maxanswers` smallint(3) NOT NULL DEFAULT 4,
  `maxattempts` smallint(3) NOT NULL DEFAULT 5,
  `review` smallint(3) NOT NULL DEFAULT 0,
  `nextpagedefault` smallint(3) NOT NULL DEFAULT 0,
  `feedback` smallint(3) NOT NULL DEFAULT 1,
  `minquestions` smallint(3) NOT NULL DEFAULT 0,
  `maxpages` smallint(3) NOT NULL DEFAULT 0,
  `timelimit` bigint(10) NOT NULL DEFAULT 0,
  `retake` smallint(3) NOT NULL DEFAULT 1,
  `activitylink` bigint(10) NOT NULL DEFAULT 0,
  `mediafile` varchar(255) NOT NULL DEFAULT '',
  `mediaheight` bigint(10) NOT NULL DEFAULT 100,
  `mediawidth` bigint(10) NOT NULL DEFAULT 650,
  `mediaclose` smallint(3) NOT NULL DEFAULT 0,
  `slideshow` smallint(3) NOT NULL DEFAULT 0,
  `width` bigint(10) NOT NULL DEFAULT 640,
  `height` bigint(10) NOT NULL DEFAULT 480,
  `bgcolor` varchar(7) NOT NULL DEFAULT '#FFFFFF',
  `displayleft` smallint(3) NOT NULL DEFAULT 0,
  `displayleftif` smallint(3) NOT NULL DEFAULT 0,
  `progressbar` smallint(3) NOT NULL DEFAULT 0,
  `available` bigint(10) NOT NULL DEFAULT 0,
  `deadline` bigint(10) NOT NULL DEFAULT 0,
  `timemodified` bigint(10) NOT NULL DEFAULT 0,
  `completionendreached` tinyint(1) DEFAULT 0,
  `completiontimespent` bigint(11) DEFAULT 0,
  `allowofflineattempts` tinyint(1) DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `mdl_less_cou_ix` (`course`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=COMPRESSED COMMENT='Defines lesson'