CREATE TABLE `mdl_scorm` (
  `id` bigint(10) NOT NULL AUTO_INCREMENT,
  `course` bigint(10) NOT NULL DEFAULT 0,
  `name` varchar(255) NOT NULL DEFAULT '',
  `scormtype` varchar(50) NOT NULL DEFAULT 'local',
  `reference` varchar(255) NOT NULL DEFAULT '',
  `intro` longtext NOT NULL,
  `introformat` smallint(4) NOT NULL DEFAULT 0,
  `version` varchar(9) NOT NULL DEFAULT '',
  `maxgrade` double NOT NULL DEFAULT 0,
  `grademethod` tinyint(2) NOT NULL DEFAULT 0,
  `whatgrade` bigint(10) NOT NULL DEFAULT 0,
  `maxattempt` bigint(10) NOT NULL DEFAULT 1,
  `forcecompleted` tinyint(1) NOT NULL DEFAULT 0,
  `forcenewattempt` tinyint(1) NOT NULL DEFAULT 0,
  `lastattemptlock` tinyint(1) NOT NULL DEFAULT 0,
  `masteryoverride` tinyint(1) NOT NULL DEFAULT 1,
  `displayattemptstatus` tinyint(1) NOT NULL DEFAULT 1,
  `displaycoursestructure` tinyint(1) NOT NULL DEFAULT 0,
  `updatefreq` tinyint(1) NOT NULL DEFAULT 0,
  `sha1hash` varchar(40) DEFAULT NULL,
  `md5hash` varchar(32) NOT NULL DEFAULT '',
  `revision` bigint(10) NOT NULL DEFAULT 0,
  `launch` bigint(10) NOT NULL DEFAULT 0,
  `skipview` tinyint(1) NOT NULL DEFAULT 1,
  `hidebrowse` tinyint(1) NOT NULL DEFAULT 0,
  `hidetoc` tinyint(1) NOT NULL DEFAULT 0,
  `nav` tinyint(1) NOT NULL DEFAULT 1,
  `navpositionleft` bigint(10) DEFAULT -100,
  `navpositiontop` bigint(10) DEFAULT -100,
  `auto` tinyint(1) NOT NULL DEFAULT 0,
  `popup` tinyint(1) NOT NULL DEFAULT 0,
  `options` varchar(255) NOT NULL DEFAULT '',
  `width` bigint(10) NOT NULL DEFAULT 100,
  `height` bigint(10) NOT NULL DEFAULT 600,
  `timeopen` bigint(10) NOT NULL DEFAULT 0,
  `timeclose` bigint(10) NOT NULL DEFAULT 0,
  `timemodified` bigint(10) NOT NULL DEFAULT 0,
  `completionstatusrequired` tinyint(1) DEFAULT NULL,
  `completionscorerequired` bigint(10) DEFAULT NULL,
  `completionstatusallscos` tinyint(1) DEFAULT NULL,
  `autocommit` tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `mdl_scor_cou_ix` (`course`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=COMPRESSED COMMENT='each table is one SCORM module and its configuration'