CREATE TABLE `mdl_quiz` (
  `id` bigint(10) NOT NULL AUTO_INCREMENT,
  `course` bigint(10) NOT NULL DEFAULT 0,
  `name` varchar(255) NOT NULL DEFAULT '',
  `intro` longtext NOT NULL,
  `introformat` smallint(4) NOT NULL DEFAULT 0,
  `timeopen` bigint(10) NOT NULL DEFAULT 0,
  `timeclose` bigint(10) NOT NULL DEFAULT 0,
  `timelimit` bigint(10) NOT NULL DEFAULT 0,
  `overduehandling` varchar(16) NOT NULL DEFAULT 'autoabandon',
  `graceperiod` bigint(10) NOT NULL DEFAULT 0,
  `preferredbehaviour` varchar(32) NOT NULL DEFAULT '',
  `canredoquestions` smallint(4) NOT NULL DEFAULT 0,
  `attempts` mediumint(6) NOT NULL DEFAULT 0,
  `attemptonlast` smallint(4) NOT NULL DEFAULT 0,
  `grademethod` smallint(4) NOT NULL DEFAULT 1,
  `decimalpoints` smallint(4) NOT NULL DEFAULT 2,
  `questiondecimalpoints` smallint(4) NOT NULL DEFAULT -1,
  `reviewattempt` mediumint(6) NOT NULL DEFAULT 0,
  `reviewcorrectness` mediumint(6) NOT NULL DEFAULT 0,
  `reviewmarks` mediumint(6) NOT NULL DEFAULT 0,
  `reviewspecificfeedback` mediumint(6) NOT NULL DEFAULT 0,
  `reviewgeneralfeedback` mediumint(6) NOT NULL DEFAULT 0,
  `reviewrightanswer` mediumint(6) NOT NULL DEFAULT 0,
  `reviewoverallfeedback` mediumint(6) NOT NULL DEFAULT 0,
  `questionsperpage` bigint(10) NOT NULL DEFAULT 0,
  `navmethod` varchar(16) NOT NULL DEFAULT 'free',
  `shuffleanswers` smallint(4) NOT NULL DEFAULT 0,
  `sumgrades` decimal(10,5) NOT NULL DEFAULT 0.00000,
  `grade` decimal(10,5) NOT NULL DEFAULT 0.00000,
  `timecreated` bigint(10) NOT NULL DEFAULT 0,
  `timemodified` bigint(10) NOT NULL DEFAULT 0,
  `password` varchar(255) NOT NULL DEFAULT '',
  `subnet` varchar(255) NOT NULL DEFAULT '',
  `browsersecurity` varchar(32) NOT NULL DEFAULT '',
  `delay1` bigint(10) NOT NULL DEFAULT 0,
  `delay2` bigint(10) NOT NULL DEFAULT 0,
  `showuserpicture` smallint(4) NOT NULL DEFAULT 0,
  `showblocks` smallint(4) NOT NULL DEFAULT 0,
  `completionattemptsexhausted` tinyint(1) DEFAULT 0,
  `completionminattempts` bigint(10) NOT NULL DEFAULT 0,
  `allowofflineattempts` tinyint(1) DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `mdl_quiz_cou_ix` (`course`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=COMPRESSED COMMENT='The settings for each quiz.'