CREATE TABLE `mdl_zoom` (
  `id` bigint(10) NOT NULL AUTO_INCREMENT,
  `course` bigint(10) NOT NULL,
  `intro` longtext DEFAULT NULL,
  `introformat` smallint(4) DEFAULT NULL,
  `grade` bigint(10) DEFAULT NULL,
  `meeting_id` bigint(15) NOT NULL,
  `start_url` longtext DEFAULT NULL,
  `join_url` longtext DEFAULT NULL,
  `created_at` varchar(20) DEFAULT NULL,
  `host_id` varchar(30) NOT NULL DEFAULT '',
  `name` varchar(300) NOT NULL DEFAULT '',
  `start_time` bigint(12) DEFAULT NULL,
  `timemodified` bigint(12) DEFAULT NULL,
  `recurring` tinyint(1) DEFAULT 0,
  `recurrence_type` tinyint(1) DEFAULT NULL,
  `repeat_interval` tinyint(2) DEFAULT NULL,
  `weekly_days` varchar(14) DEFAULT NULL,
  `monthly_day` tinyint(2) DEFAULT NULL,
  `monthly_week` tinyint(2) DEFAULT NULL,
  `monthly_week_day` tinyint(1) DEFAULT NULL,
  `monthly_repeat_option` tinyint(1) DEFAULT NULL,
  `end_times` tinyint(2) DEFAULT NULL,
  `end_date_time` bigint(12) DEFAULT NULL,
  `end_date_option` tinyint(1) DEFAULT NULL,
  `webinar` tinyint(1) DEFAULT 0,
  `duration` mediumint(6) DEFAULT NULL,
  `timezone` varchar(50) DEFAULT NULL,
  `password` varchar(10) DEFAULT NULL,
  `option_jbh` tinyint(1) DEFAULT 0,
  `option_start_type` varchar(12) DEFAULT NULL,
  `option_host_video` tinyint(1) DEFAULT 0,
  `option_participants_video` tinyint(1) DEFAULT 0,
  `option_audio` varchar(9) DEFAULT 'both',
  `option_mute_upon_entry` tinyint(1) DEFAULT 1,
  `option_waiting_room` tinyint(1) DEFAULT 1,
  `option_authenticated_users` tinyint(1) DEFAULT 0,
  `option_encryption_type` varchar(20) DEFAULT 'enhanced_encryption',
  `exists_on_zoom` tinyint(1) NOT NULL DEFAULT 1,
  `alternative_hosts` longtext DEFAULT NULL,
  `recordings_visible_default` tinyint(1) NOT NULL DEFAULT 1,
  `show_schedule` tinyint(1) NOT NULL DEFAULT 1,
  `show_security` tinyint(1) NOT NULL DEFAULT 1,
  `show_media` tinyint(1) NOT NULL DEFAULT 1,
  `option_auto_recording` varchar(5) DEFAULT NULL,
  `registration` tinyint(1) NOT NULL DEFAULT 2,
  PRIMARY KEY (`id`),
  KEY `mdl_zoom_mee_ix` (`meeting_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=COMPRESSED COMMENT='Zoom meetings and webinars'